services:
  postgres:
    network_mode: host
    image: postgres:latest
    container_name: BookWave
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: BookWave
    expose:
      - "5433"
    ports:
      - "5433:5433"
    command: -p 5433
